claim/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import permission_required
from .views import ClaimCreate, ClaimUpdate, ClaimSpam, ClaimList, ManyClaimsAction

pr = permission_required('can_work_with_claims', raise_exception=True)

urlpatterns = patterns('',
                       url(r'^new/$', pr(ClaimCreate.as_view()), name='new-claim'),
                       url(r'^edit/(?P<pk>\d+)/$', pr(ClaimUpdate.as_view()), name='edit-claim'),
                       url(r'^spam/(?P<pk>\d+)/$', pr(ClaimSpam.as_view()), name='to-spam-claim'),
                       url(r'^multi/$', pr(ManyClaimsAction.as_view()), name='multi-action'),
                       url(r'^$', pr(ClaimList.as_view()), name='claim-list'),
                       )

main/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import permission_required
from django.views.generic import TemplateView
from django.contrib.flatpages import views
from functools import partial
from pay.views import PayView, LogView, BankFileView, BankRecordsListView, ExportPay, DeletePay
from metric.views import ConfigView, YandexVerificationView, DashboardView, TopView
admin.autodiscover()

pr = partial(permission_required, raise_exception=True)

urlpatterns = patterns(
    '',
    url('^logout/', 'django.contrib.auth.views.logout_then_login', name="logout_then_login"),
    url('^login/', 'django.contrib.auth.views.login', name="login"),
    url(r'^log$', pr('pay.can_view_payinfo')(LogView.as_view()), name='log'),
    url(r'^export/(?P<pk>\d+)/$', pr('pay.can_view_payinfo')(ExportPay.as_view()), name='pay_export'),
    url(r'^delete/(?P<pk>\d+)/$', pr('pay.can_del_payinfo')(DeletePay.as_view()), name='pay_delete'),
    url(r'^pay$', pr('pay.can_add_payinfo')(PayView.as_view()), name='pay'),
    url(r'^import_bank$', pr('pay.can_add_payinfo')(BankFileView.as_view()), name='import_bank'),
    url(r'^select_bank/(?P<pk>\d+)/$', pr('pay.can_add_payinfo')(BankRecordsListView.as_view()), name='select_bank'),
    url(r'^config$', ConfigView.as_view(), name='config'),
    url(r'^process_yandex_code$', YandexVerificationView.as_view(), name='process_yandex_code'),
    url(r'^top$', pr('metric.can_view_top')(TopView.as_view()), name='top'),
    url(r'^dasboard_data/', include('metric.urls')),
    url(r'^claims/', include('claim.urls')),
    url(r'^stat/$', pr('metric.can_view_stat')(DashboardView.as_view()), name='dashboard'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^forum/', TemplateView.as_view(template_name='forum.html'), name='forum'),
    url(r'^forum_iframe/', include('spirit.urls')),
)

urlpatterns += patterns(
    '',
    url(r'^ckeditor/', include('ckeditor.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns(
    "",
    url(r'^docs/$', views.flatpage, {'url': '/docs/'}, name='docs'),
    url(r'^', include('django.contrib.flatpages.urls')),
)

claim/models.py
from xml.etree.ElementTree import Element, tostring
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.conf import settings
from lxml import html as lh
from lxml.html import defs
import re
from pay.imap_fetcher import ImapFetcher
from pay.models import FtpExporter
from .tasks import export_claim


class ClaimFtpExporter(FtpExporter):
    base_folder = settings.FTP_FOLDER_CLAIM


class XmlDict(dict):

    def to_xml(self, root_tag='root'):
        elem = Element(root_tag)
        for key, val in self.items():
            child = Element(key)
            child.text = str(val)
            elem.append(child)
        return tostring(elem, encoding='windows-1251')
        # return b'<?xml version="1.0" encoding="windows-1251"?>\n' + xml_bytes


class Claim(models.Model):

    DELIVERY_POST = "post"
    DELIVERY_COURIER = "courier"
    DELIVERY_SELF = "self"
    DELIVERY_EMS = "ems"
    DELIVERY_TRANSPORT = "transport"
    DELIVERY_COURIER_RUSSIA = "courier_russia"
    DELIVERY_SELF_PROLETARSKAYA = "self_proletarskaya"
    DELIVERY_SELF_STROGINO = "self_strogino"
    DELIVERY_SELF_SCHUKINSKAYA = "self_schukinskaya"

    DELIVERY_CHOISES = (
        (DELIVERY_POST, 'Почтой'),
        (DELIVERY_COURIER, 'Курьером'),
        (DELIVERY_SELF, 'Самовывоз'),
        (DELIVERY_EMS, 'Экспресс доставка через EMS почту'),
        (DELIVERY_TRANSPORT, 'Транспортная компания'),
        (DELIVERY_COURIER_RUSSIA, 'Курьерская доставка в города России'),
        (DELIVERY_SELF_PROLETARSKAYA, 'Самовывоз Пролетарская'),
        (DELIVERY_SELF_STROGINO, 'Самовывоз Строгино'),
        (DELIVERY_SELF_SCHUKINSKAYA, 'Самовывоз Щукинская'),
    )

    PAY_CASH = 'cash'
    PAY_BANK = 'bank'
    PAY_EMONEY = "emoney"
    PAY_OTHER = "other"

    PAY_CHOICES = (
        (PAY_CASH, 'Наличными при получении'),
        (PAY_BANK, 'Оплата через банк'),
        (PAY_EMONEY, 'Электронные деньги'),
        (PAY_OTHER, 'Другой способ оплаты'),
    )

    sender = models.CharField('Отправитель', max_length=255)
    subject = models.CharField('Тема', max_length=255, null=True, blank=True)
    message = models.TextField('Сообщение', null=True, blank=True)
    comment = models.TextField('Комментарий оператора', blank=True, null=True)
    order_num = models.IntegerField('Номер заказа', blank=True, null=True)
    delivery_method = models.CharField(
        'Способ доставки', max_length=20, choices=DELIVERY_CHOISES, blank=True, null=True)
    pay_form = models.CharField('Способ оплаты', max_length=50, choices=PAY_CHOICES, blank=True, null=True)
    manager = models.ForeignKey(User, verbose_name='Менеджер', null=True)
    sended_on = models.DateTimeField('Дата отправки', default=timezone.now, db_index=True)
    is_spam = models.BooleanField(u'Спам', default=False, db_index=True)
    email_uid = models.IntegerField(u'UID email', null=True, default=None, unique=True)
    seen = models.BooleanField(u'Просмотрено', default=False)
    exported = models.BooleanField(u'Выгружено', default=False)

    class Meta:
        verbose_name = "Обращение"
        verbose_name_plural = "Обращения"
        default_permissions = ()
        permissions = (
            ('can_work_with_claims', "Может работать с обращениями"),
        )
        ordering = ['-sended_on']

    def __str__(self):
        return "Обращение {0.pk}: {0.subject}".format(self)

    def get_absolute_url(self):
        return reverse('edit-claim', kwargs={'pk': self.pk})

    def export(self):
        data = XmlDict(
            sender=self.sender,
            subject=self.subject,
            message=self.message,
            comment=self.comment,
            order_num=self.order_num,
            delivery_method=self.get_delivery_method_display(),
            pay_form=self.get_pay_form_display(),
            manager=self.manager,
            sended_on=self.sended_on,
        )
        filename = "{}.xml".format(self.id)
        export_claim.apply_async((data.to_xml(), filename))

    @property
    def is_seen_display(self):
        value = self.seen
        if not self.seen:
            self.seen = True
            self.save(update_fields=['seen'])
        return value

    @classmethod
    def update_from_email(cls):
        latest_email = cls.objects.exclude(email_uid=None).order_by('-email_uid').first()
        if latest_email is None:
            last_uid = 0
        else:
            last_uid = latest_email.email_uid
        fetcher = ImapFetcher(
            settings.IMAP_HOST,
            settings.IMAP_PORT,
            settings.IMAP_CLAIM_LOGIN,
            settings.IMAP_CLAIM_PASSWORD)
        ids = fetcher.get_ids_greater(last_uid)
        for m_id in ids:
            data = fetcher.get_message_info(m_id)
            if cls.objects.filter(email_uid=data.uid).exists():
                continue
            obj = cls(
                email_uid=data.uid,
                subject=data.subject,
                sender=data.sender
            )
            # obj.sended_on = fetcher.get_message_date(m_id)
            content, date, content_subtype = fetcher.get_email_content(m_id, desired_part=('text', 'plain'))
            obj.sended_on = date
            if len(content) > 10 and content_subtype.lower() == 'html':
                doc = lh.fromstring(content)
                for node in doc.iter():
                    if node.tag in defs.block_tags:
                        if node.text is not None:
                            node.text += "\n"
                    elif node.tag == 'br':
                        if node.tail is not None:
                            node.tail += '\n'
                        else:
                            node.tail = '\n'
                content = lh.tostring(doc, method='text', encoding=str, pretty_print=True)
            content = re.sub('(\r?\n)+', '\n', content)
            obj.message = content.strip()
            obj.save()

claim/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from urllib import parse
from .models import Claim


class ExportMixin(object):

    def form_valid(self, form):
        form.instance.manager = self.request.user
        form.instance.exported = True
        form.instance.seen = True
        form.instance.save()
        form.instance.export()
        messages.success(self.request, 'Запись "{0.subject}" выгружена'.format(form.instance))
        return super(ExportMixin, self).form_valid(form)


class ClaimCreate(ExportMixin, CreateView):
    template_name = "claim/form.html"
    model = Claim
    fields = [
        "sender",
        "subject",
        "message",
        "comment",
        "order_num",
        "delivery_method",
        "pay_form",
    ]
    success_url = reverse_lazy('claim-list')


class ClaimUpdate(ExportMixin, UpdateView):
    template_name = "claim/form.html"
    model = Claim
    fields = [
        "sender",
        "subject",
        "message",
        "comment",
        "order_num",
        "delivery_method",
        "pay_form",
    ]

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        next_url = self.request.GET.get('next')
        multi_action = True
        if next_url is None:
            multi_action = False
            next_url = self.request.META.get('HTTP_REFERER')
        context['next'] = parse.quote(next_url)
        context['multi_action'] = multi_action
        return context

    def get_success_url(self, *args, **kwargs):
        return self.request.GET.get('next', reverse_lazy('claim-list'))


class ClaimSpam(SingleObjectMixin, RedirectView):
    model = Claim
    url = reverse_lazy('claim-list')
    permanent = False

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_spam = True
        self.object.save()
        messages.success(request, 'Запись "{0.subject}" помечена как спам'.format(self.object))
        return super(ClaimSpam, self).get(request, *args, **kwargs)


class ManyClaimsAction(RedirectView):
    permanent = False
    pattern_name = 'claim-list'
    query_string = True
    ids_get_param = "ids"
    fin_url_get_param = "fin"

    def get_pks(self):
        return self.request.GET.getlist(self.ids_get_param)

    def get_fin_url(self):
        fin_url = self.request.GET.get(self.fin_url_get_param)
        if fin_url is None:
            fin_url = self.request.META.get('HTTP_REFERER')
        return fin_url

    def process_spam(self, *args, **kwargs):
        pks = self.get_pks()
        fin_url = self.get_fin_url()
        count = Claim.objects.filter(pk__in=pks).update(is_spam=True)
        messages.success(self.request, '{} записей помечено как спам'.format(count))
        return fin_url

    def process_export(self, *args, **kwargs):
        pks = self.get_pks()
        fin_url = self.get_fin_url()
        if len(pks) > 0:
            pk = pks.pop(0)
            url = reverse_lazy('edit-claim', kwargs={'pk': pk})
            next_url = reverse_lazy('multi-action')
            next_url += '?' + parse.urlencode({
                self.ids_get_param: pks,
                self.fin_url_get_param: fin_url
            }, doseq=True)
            return "{}?{}".format(url, parse.urlencode({'next': next_url}))
        else:
            return fin_url

    def get_redirect_url(self, *args, **kwargs):
        action = self.request.GET.get('action', 'export')
        method = getattr(self, 'process_{}'.format(action))
        return method(*args, **kwargs)


class ClaimList(ListView):
    queryset = Claim.objects.exclude(is_spam=True)
    template_name = "claim/list.html"
    paginate_by = 25

claim/templates/claim/form.html
{% extends "logged_layout.html" %}
{% load bootstrap3 %}
{% block content %}
    {% bootstrap_messages %}
    {# <h2>Ручной ввод платежа</h2> #}
    {# Display a form #}
    <form action="?next={{ next }}" method="post" class="form form-horizontal">
        {% csrf_token %}
          {% bootstrap_form form layout='horizontal' %}
          {% buttons %}
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">{{ multi_action|yesno:'Сохранить и перейти к следующему обращению,Сохранить'}}</button>
        </div>
        {% endbuttons %}
    </form>
{% endblock content %}

claim/templates/claim/list.html
{% extends "logged_layout.html" %}
{% load staticfiles %}
{% load bootstrap3 %}
{% block headscript %}
    <link rel="stylesheet" type="text/css" href="{% static "css/claim.css" %}">
{% endblock headscript %}
{% block content %}
{% bootstrap_messages %}
<div class="row">
    <div class="col-md-12">
        <a class="btn btn-primary" href="{% url 'new-claim' %}"><i class="glyphicon glyphicon-plus"></i> Добавить запись</a>
    </div>
</div>
{% if is_paginated %}
    {% bootstrap_pagination page_obj %}
{% endif %}
<form action="{% url 'multi-action' %}">
    <div class="btn btn-group">
        <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-share-alt"></i> Выгрузить отмеченные</button>
        <button type="submit" class="btn btn-default" name="action" value="spam"><i class="glyphicon glyphicon-trash"></i> Поместить в спам</button>
    </div>
    <table class="table" id="claim-list">
    <colgroup />
    <colgroup />
    <colgroup width="20%"/>
    <colgroup width="50%"/>
    <colgroup />
    <colgroup  width="10%"/>
        <thead>
            <tr>
                <td><input type="checkbox" class="check-all"></td>
                <th>ID</th>
                <th>Автор | Тема</th>
                <th>Сообщение</th>
                <th>Дата отправки</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
            {% for claim in claim_list %}
                <tr class="{% if not claim.is_seen_display %}
                    info
                {% endif %}
                {% if claim.exported %}
                    success
                {% endif %}
                ">
                    <td><input type="checkbox" name="ids" value="{{ claim.id }}"></td>
                    <td>{{ claim.email_uid }}</td>
                    <td class="wrap-words">
                        <a href="mailto:{{ claim.sender }}">{{ claim.sender }}</a> <br/>
                        {{ claim.subject|truncatechars:50 }}
                    </td>
                    <td class="wrap-words">{{ claim.message|linebreaksbr|truncatechars_html:160 }}</td>
                    <td>{{ claim.sended_on }}</td>
                    <td>
                        <div class="btn btn-group btn-group-xs">
                            
                            <a class="btn btn-default btn-small" href="{% url 'edit-claim' pk=claim.pk %}"><i class="glyphicon glyphicon-share-alt" title="Выгрузить"></i></a>
                            <a class="btn btn-default btn-small" href="{% url 'to-spam-claim' pk=claim.pk %}"><i class="glyphicon glyphicon-trash" title="Спам"></i></a>
                        </div>
                    </td>
                </tr>
            {% empty %}
            <tr>
                <td colspan="5">Нет записей</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</form>
{% if is_paginated %}
    {% bootstrap_pagination page_obj %}
{% endif %}
{% endblock content %}
{% block script %}
    <script type="text/javascript">
    (function(jQuery){
        var $ = jQuery;
        var claimTable = $('#claim-list');
        var claimCheckboxes = claimTable.find('tbody :checkbox');
        claimTable.find('thead :checkbox').change(function(){
            var state = $(this).prop('checked');
            claimCheckboxes.prop('checked', state);
        })
    }
    )($)
    </script>
{% endblock script %}